/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TimeSumPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var TimeSumPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.onLayoutChange = async () => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView && activeView.getMode() === "preview") {
        const file = activeView.file;
        if (!file)
          return;
        const oldContent = await this.app.vault.cachedRead(file);
        const newContent = this.calculateTime(oldContent);
        if (oldContent !== newContent) {
          await this.app.vault.modify(file, newContent);
        }
      }
    };
  }
  async onload() {
    this.addCommand({
      id: "sum-time-durations",
      name: "Sum time durations",
      editorCallback: (editor, view) => {
        const oldContent = editor.getValue();
        const newContent = this.calculateTime(oldContent);
        if (oldContent !== newContent) {
          editor.setValue(newContent);
        }
      }
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", this.onLayoutChange)
    );
  }
  onunload() {
    this.app.workspace.off("layout-change", this.onLayoutChange);
  }
  calculateTime(content) {
    const timeRegex = /\((\s*(?:(\d+)\s*w)?\s*(?:(\d+)\s*d)?\s*(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?\s*)\)/g;
    const blockRegex = /(```time-sum\n)([\s\S]*?)(```)/;
    if (!blockRegex.test(content)) {
      return content;
    }
    let totalMinutes = 0;
    let match;
    const contentWithoutBlock = content.replace(blockRegex, "");
    while ((match = timeRegex.exec(contentWithoutBlock)) !== null) {
      const weeks = parseInt(match[2]) || 0;
      const days = parseInt(match[3]) || 0;
      const hours = parseInt(match[4]) || 0;
      const minutes = parseInt(match[5]) || 0;
      totalMinutes += weeks * 7 * 24 * 60 + days * 24 * 60 + hours * 60 + minutes;
    }
    let formattedTime = "0m";
    if (totalMinutes > 0) {
      const outDays = Math.floor(totalMinutes / (24 * 60));
      const remainingMinutes = totalMinutes % (24 * 60);
      const outHours = Math.floor(remainingMinutes / 60);
      const outMinutes = remainingMinutes % 60;
      let tempTime = "";
      if (outDays > 0)
        tempTime += `${outDays}d `;
      if (outHours > 0)
        tempTime += `${outHours}h `;
      if (outMinutes > 0)
        tempTime += `${outMinutes}m`;
      formattedTime = tempTime.trim();
    }
    return content.replace(blockRegex, `$1${formattedTime}
$3`);
  }
};
